### ISSUE TITLE
Interface is humongous

### ISSUE THREAD

**Issue by LoganDark** [nickgravgaard/ElasticNotepad#10]
![image](https://user-images.githubusercontent.com/4723091/189192108-dd71b5e0-264c-4012-a4ec-f43810d1f5da.png)

The interface of this application is absolutely huge, even the window title is about double the size of what it should be (comparing with notepad.exe)

Even if I change the size of the font in-editor the interface stays huge:

![image](https://user-images.githubusercontent.com/4723091/189195182-d5015a24-8ff4-4a51-a80e-2366373c0290.png)

4K display with 200% scale factor on Windows 10, Java 17

**Comment by nickgravgaard** [comment]
Hi there. It is a bit big isn't it? I've just released a new version which reduces the default scale multiplier and font sizes a bit. It also adds a Scale setting so you can tweak it to whatever makes sense for your system. Hope that helps!

**Comment by LoganDark** [comment]
That is much better, thank you~

![image](https://user-images.githubusercontent.com/4723091/189505429-020f7746-e165-4fba-9b0c-1a01a033bce0.png)
