### ISSUE TITLE
Interaction with code formatters

### ISSUE THREAD

**Issue by bugabinga** [nickgravgaard/ElasticNotepad#3]
Hi!

While the concept of ETs is simple and easy to understand, the implications are not yet clear to me.

Do typical code formatters _destroy_ ETs by replacing tabs with spaces or somesuch?
I will test this later in my texteditor. But even then, I couldn't be sure if any observed behaviour is simply a bug in the editor/plugin.

**Comment by nickgravgaard** [comment]
Many tools don't know about elastic tabstops, so they will output files using spaces or non-elastic mod-N tabs. However, Elastic Notepad can be made to convert from spaces to elastic tabstops when you load a file, and convert back to spaces when you save. The idea is that this will allow people to work in teams that use spaces, but enjoy the benefits of elastic tabstops when editing text. To enable that functionality change the "Files on disk are non-elastic" setting to "true".

Before you do that it's probably a good idea to check that Elastic Notepad will handle files generated by your code formatter properly. To do this, make sure elastic mode is off, load a space formatted file, and then turn elastic mode on. Hopefully everything will be visually lined up in the same way as it was before you changed mode.

At some point I plan to make Elastic Notepad guess whether a file uses spaces or elastic tabstops and set elastic mode accordingly.

Does that make sense? Which code formatter do you have in mind?

**Comment by bugabinga** [comment]
Thanks for explaining.

I have integrated the [Google Java Formatter](https://github.com/google/google-java-format) into a [fork of ElasticNotepad](https://github.com/bugabinga/ElasticNotepad) for some experiments.
To my surprise, the most naive implementation yields seemingly compatible results.
By that I mean, given the following Java source file:

```java
/*
 * (some license) (copyright) (some year) (someone)
 */
/**
 * This is a canonical __Hello World__-Style Java class. It's purpose is to experiment with the
 * interaction between a formatter and elastic tabstops.
 */
public class Main {
	/** Sending out greeting to space! */
	public static void main(String[] args) {
		//	Elastic	Tabstops
		//	Variable	Fonts
		//	In my	Code editors
		//	adjust the length of text here...	123
		System.out.println("Hello E.T.!");
	}
}
```

After calling the __format action__, the editor is still respecting ETs, even though almost all whitespace characters got adjusted.

Do you have ideas how to make this fail :) ?

Also, is there a easy method of drawing whitespace characters with some (semi-opaque) character symbols?
It would help me understand what exactly changed in the file.

> At some point I plan to make Elastic Notepad guess whether a file uses spaces or elastic tabstops and set elastic mode accordingly.

Would that be part of the generic ET algorithm or specific to the editor?

**Comment by nickgravgaard** [comment]
> After calling the **format action**, the editor is still respecting ETs, even though almost all whitespace characters got adjusted.
>
> Do you have ideas how to make this fail :) ?

What exactly was the text before and after calling the format action?

One of the advantages of elastic tabstops is that when you make text in one column longer, the whitespace (tabs) in the buffer doesn't change, only the way the text is displayed (the tabstops are moved). Does that explain what you saw?

> Also, is there a easy method of drawing whitespace characters with some (semi-opaque) character symbols?

I just searched quickly and found [this](http://java-sl.com/showpar.html). In the future I plan to swap the JTextPane for something like [RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea) which I think can do this.

>>At some point I plan to make Elastic Notepad guess whether a file uses spaces or elastic tabstops and set elastic mode accordingly.
>
>Would that be part of the generic ET algorithm or specific to the editor?

My first attempt at a solution might be as trivial as just checking if the file contains any tab characters. If it does, assume it is using elastic tabstops so use elastic mode, otherwise assume it is using spaces so use non-elastic mode.
