### ISSUE TITLE
Is there a way to configure windows to open a file with ElasticNotepad?

### ISSUE THREAD

**Issue by drwhite729** [nickgravgaard/ElasticNotepad#5]
For a simple solution, what can I put in my "SendTo" folder so that I can send a file to ElasticNotepad and have the editor start with that file open?

**Comment by nickgravgaard** [comment]
You can't at the moment I'm afraid, since the program doesn't take any parameters yet. It's a bit of a glaring omission, so I'll fix it and get back to you here.

**Comment by drwhite729** [comment]
Thank you; that will be nice when it's ready.  I'm looking forward to it.

**Comment by nickgravgaard** [comment]
Hi Daniel, I've just released a new version (1.5.0) which adds a filename command-line argument. Please give it a try and see how you get on.
