### ISSUE TITLE
Mouse click hit-testing is weird

### ISSUE THREAD

**Issue by LoganDark** [nickgravgaard/ElasticNotepad#9]
Right now, it looks like clicking anywhere in a character puts the cursor at the end of it. It would be much more intuitive if the partition point was in the middle, so clicking near the start of the tab would position your cursor at the start.

Here's a video of me trying very hard to position my cursor at the start of some tabs

https://user-images.githubusercontent.com/4723091/189191789-3bcd4705-7797-4989-b4bc-3a511027351a.mp4

**Comment by nickgravgaard** [comment]
Hmm, this is Swing's default behaviour, and I imagine it's quite hard to change. I don't think I'm going to get the time to fix this, but I'd consider a PR if you or anyone else wants to do it.

**Comment by LoganDark** [comment]
I can't figure out your build system (which is also why I wasn't using version 1.8 before, because I couldn't figure out how to build the jar)

**Comment by LoganDark** [comment]
Ugh I can't get IntelliJ to work at all. I used Linux to generate project files and opened it up, and I'm getting this

![image](https://user-images.githubusercontent.com/4723091/189506157-033b9e4d-0312-4c63-b26e-c7506b65bbfa.png)

Why does IntelliJ always do this...

**Comment by LoganDark** [comment]
Ughhh, okay this is way more complicated than I thought it would be.

Basically the mouse hit-test is buried behind about 5 layers of Enterprise-Grade Indirection, but the meat of it is in `javax.swing.text.Utilities#getTabbedTextOffset`, which is a freaking mess. It has an option to round the bias (which is the fancy name for "which side of the character you clicked your caret ends up on"), but it doesn't seem to work properly, or at least, works inconsistently.

I have a hunch that this could be due to how the elastic tabstops are implemented because the method is being called with `round == true`. My debugger works so I'm going to step through and try to understand how this function works. Stay tuned...

**Comment by LoganDark** [comment]
Hittest thinks the length of a tab is 0

![image](https://user-images.githubusercontent.com/4723091/189506746-082ad99e-5817-4073-a4c9-33aa31cc4009.png)

It *can* calculate the length of the tab using the provided tab expander, which is why hit tests work OK usually, but `getFontCharsWidth` can't, and assumes all tabs are width-0

I can actually predict what happens and then verify it: On any character on a line *before* a tab, the rounding works properly- clicking to the left or right "side" of a character positions the caret correctly

But if you click on a character where at least 1 tab exists earlier in the line, then the rounding will think earlier tab is width-0 (thanks to `getFontCharsWidth`), see your cursor is way to the right of that, and *always* place your caret to the right of the character you clicked

Here is a video of the issue: (every time my caret moves is a click)

https://user-images.githubusercontent.com/4723091/189507315-14cbfb64-9aba-4d0a-9475-8394cae6abcc.mp4

There is no reasonable way for Elastic Notepad to swap out this algorithm, so I think this issue unfortunately has to be closed as a "cantfix" :(

Maybe the way to fix this is to choose a different way of expanding tabs, but the method you use seems to work fine in all other cases...

**Comment by LoganDark** [comment]
There's one possible solution which is to create a wrapper around the `java.awt.Font` (subclass maybe?), so that `getFontCharsWidth` will get a correct result when it calls the font's `getStringBounds` method. But I'm still not quite sure how tab stop information would get there.

**Comment by nickgravgaard** [comment]
Wow, thanks for trying to figure this out @LoganDark!

**Comment by LoganDark** [comment]
> Wow, thanks for trying to figure this out @LoganDark!

Of course, but I don't know Scala or how your implementation of elastic tabs works at all, so I can't go any further. You'll have to do your own testing if you want to try that hacky workaround, but otherwise I'm at least glad I know what the issue is.
